While attempted to build James based on the current Avalon CVS of Cornerstone and I'm experiencing a ClassCastException.  The James implementation is referencing DefaultThreadManager as a Component, however, the "implements Component" clause has been removed from the defintion without modification of any versioning information breaking backward compatibility with the James implementation. The solution is to re-include the Component interface into the implements statement which has no side-effects and will not impact any other usage of this class.  If someone has an objectition to this, please feel free to post a detailed explination to the Avalon Dev list. A stack trace demonstrating the issue is included below:
[ERROR  ] (root.james): Container disposal triggered by abnormal condition.
org.apache.excalibur.merlin.container.ContainerException: Unexpected error during container execution.
        at org.apache.excalibur.merlin.container.DefaultContainer.run(Unknown Source)
        at java.lang.Thread.run(Thread.java:536)
Caused by: org.apache.excalibur.merlin.resource.LifecycleException: Component named "/root/james/spool" failed to pass through the Composing
 stage. (Reason: org.apache.avalon.framework.component.ComponentException: Service provider returned a non-Component: class org.apache.avalon.cornerstone.blocks.threads.DefaultThreadManager).
        at org.apache.excalibur.merlin.resource.LifecycleHelper.fail(Unknown Source)
        at org.apache.excalibur.merlin.resource.LifecycleHelper.startup(Unknown Source)
        at org.apache.excalibur.merlin.resource.AbstractLifestyleHandler.createInstance(Unknown Source)
        at org.apache.excalibur.merlin.resource.SingletonLifestyleHandler.get(Unknown Source)


git-svn-id: https://svn.apache.org/repos/asf/avalon/trunk@14566 13f79535-47bb-0310-9956-ffa450edef68